### PR TITLE
Increase dependency version bounds

### PR DESCRIPTION
**Pull request by neilmayhew**
* aeson
* proto-lens-runtime
* servant

---
This change is [Reviewable](https://reviewable.io/reviews/tclem/twirp-haskell/20)

### CODE REVIEW

**Comment by tclem** [comment]
Nice, I'll take a look once the builds are green.

**Comment by neilmayhew** [comment]
I don't think this is going to work until a new version of `proto-lens-jsonpb` is pushed to Hackage, because AFAICT this project uses `proto-lens-jsonpb` from Hackage not from its repo.

**Comment by neilmayhew** [comment]
I noticed this had the same problem with not updating the example project. I've fixed this, and built it locally by temporarily adding `../proto-lens-jsonpb` to `packages` in `cabal.project`, but it's not going to succeed in CI until `proto-lens-jsonpb` is updated on Hackage.

**Comment by neilmayhew** [comment]
You could add this to `cabal.project`:

```
source-repository-package
    type: git
    location: https://github.com/tclem/proto-lens-jsonpb
```

It would cause this project to build with `master` from `proto-lens-jsonpb`.

**Comment by tclem** [comment]
Alright, a new [proto-lens-jsonpb 0.2.0.1](https://hackage.haskell.org/package/proto-lens-jsonpb-0.2.0.1) is published, do you mind doing a similar thing here with making the version bounds inclusive?

**Comment by tclem** [comment]
Thanks again @neilmayhew and apologies for the slow response here, I didn't notice your last push.

I sorted out some conflicts with master and merged this in ✨ .

**Comment by neilmayhew** [comment]
Thanks, @tclem.

However, the version bounds have ended up tighter than I would have liked (as a result of #21). In particular, some of the lower bounds have been raised when I don't think they needed to be, and this will make it impossible to use `twirp-haskell` with an older Stackage snapshot. This doesn't affect me currently, but I'll do some testing and let you know what I find.

**Comment by tclem** [comment]
Oh, you're right. @rewinfrey was there something with ghc 8.10.1 that required raising the version bounds https://github.com/tclem/twirp-haskell/pull/21? Or can we relax those back again?

**Pull request merged**
