### PR TITLE
Avoid overwriting Twirp error responses returned by the application 

### PR DESCRIPTION
**Pull request by neilmayhew**
My application returns Twirp errors explicitly, by wrapping a `TwirpError` in the body of a `ServerError` and setting the status code according to the [spec](https://github.com/twitchtv/twirp/blob/master/docs/errors.md). I'm also using the `twirpErrorResponses` middleware so that errors detected by Servant before it calls my application will be returned as Twirp errors. However, `twirpErrorResponses` overwrites my carefully-crafted Twirp errors with generic ones based purely on the status code, and loses information as a result. This change adds logic to detect whether the error is already a Twirp error, and modifies it only if it's not.

The heuristic for whether an error response is already a Twirp error is a bit weak, based simply on whether the body is JSON. However, it's difficult to do better than this because WAI actively discourages you from examining the body of a response since these are designed to be streamed. It does let you look at the headers, though, so looking for a `ContentType` of `application/json` is easy and seems good enough, since it's very unlikely that any non-application error response is going to be JSON-encoded.

---
This change is [Reviewable](https://reviewable.io/reviews/tclem/twirp-haskell/22)

### CODE REVIEW

**Comment by neilmayhew** [comment]
It looks like servant may now have [a better way](https://github.com/haskell-servant/servant/blob/master/doc/cookbook/custom-errors/CustomErrors.lhs) to do all of this. However, I haven't figured out yet exactly how to make it fit with `twirp-haskell`.

**Comment by neilmayhew** [comment]
Servant's error formatting doesn't cover all possible errors, unfortunately. See https://github.com/haskell-servant/servant/issues/1341.

**Comment by tclem** [comment]
Makes sense and this looks like an appropriate solution.

@neilmayhew I'm happy to publish another version to hackage with these changes if that's helpful. Anything else you'd like to get in there before I do that?

**Review by tclem — APPROVED** [review]

**Comment by neilmayhew** [comment]
Thanks for asking. There are a couple of things I've found inconvenient on the code-generation side. I'll open a separate issue for this.

**Pull request merged**
